### ISSUE TITLE
How run sel4 test on TX2 board?

### ISSUE THREAD

**Issue by wjhtinger** [seL4/sel4test#57] opened 2021-11-09 11:10 UTC
I have build the sel4test by following this guide: https://docs.sel4.systems/Hardware/JetsonTX2.html#building-sel4test, and get the sel4test-driver-image-arm-tx2 file successfully.
But how to run the image on TX2 board? I have tested to use uboot cmdline by tftp to load the image, but cant run.
Anyone can give some guide how run on TX2 board?
Thanks.

Below is the uboot log FYR:
Tegra186 (P2771-0000-500) # tftp 0x80a88000 sel4test-driver-image-arm-tx2;go 0x80a88000
ethernet@2490000 Waiting for PHY auto negotiation to complete...... done
Using ethernet@2490000 device
TFTP from server 192.168.42.16; our IP address is 192.168.42.17
Filename 'sel4test-driver-image-arm-tx2'.
Load address: 0x80a88000
Loading: #################################################################
#################################################################
#################################################################
#################################################################
#################################################################
#################################################################
###########
993.2 KiB/s
done
Bytes transferred = 5874752 (59a440 hex)

Starting application at 0x80A88000 ...
"Synchronous Abort" handler, esr 0x02000000
ELR: 80a88000
LR: fff3d3d4
x0 : 0000000000000001 x1 : 00000000ffb3a5a8
x2 : 00000000ffb3a5a8 x3 : 0000000080a88000
x4 : 0000000000000000 x5 : 0000000000000030
x6 : 00000000fff87775 x7 : 000000000000000f
x8 : 00000000ffb2fe70 x9 : 0000000000000008
x10: 00000000ffb2f6fa x11: 0000000000000008
x12: 00000000ffffffff x13: 0000000000000200
x14: 0000000000000004 x15: 0000000000000000
x16: 0000000000002090 x17: 0000000000000001
x18: 00000000ffb32de0 x19: 00000000ffb3a5a8
x20: 0000000000000002 x21: 0000000080a88000
x22: 00000000ffb3a5a0 x23: 00000000fffaa7f4
x24: 0000000000000002 x25: 0000000000000000
x26: 0000000000000000 x27: 0000000000000000
x28: 00000000ffb3a600 x29: 00000000ffb2ffc0

Resetting CPU ...

resetting ...

**Comment by kent-mcleod** [comment] 2021-11-10 23:41
Duplicate of https://github.com/seL4/sel4test-manifest/issues/17

**Closed by kent-mcleod** 2021-11-10 23:41 UTC
